FROM ruby:3.0.3 as ruby

RUN apt-get update -qq && apt-get install -y nodejs mariadb-client

RUN mkdir /srv/Alithya-ANM-WEB

WORKDIR /srv/Alithya-ANM-WEB

COPY Gemfile /srv/Alithya-ANM-WEB

RUN bundle install

COPY . /srv/Alithya-ANM-WEB

RUN rm -rf Gemfile.lock

CMD [ "bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml" ]