default: &default
  adapter: mysql2
  #host: db
  host: localhost
  timeout: 5000
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: anm_furloughs_development
  #username: Alithya
  #password: alithya_maroc
  username: root
  password: 
